# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

fastlane_version 2.5

platform :ios do

        desc "Set framework version, creates appropriate git commit, git tag, and pushes all to our local podspec repo."
        desc "version: framework version, required!"
	lane :deploy do |options|

                ensure_git_status_clean()

                version_bump_podspec(options)

                version = lane_context[SharedValues::PODSPEC_VERSION_NUMBER]

                increment_version_number(version_number:version)

                commit_version_bump(xcodeproj:"AKPickerViewSample.xcodeproj", include:"AKPickerView-Swift.podspec", message:"AKPickerView-Swift version #{version}") unless Actions.sh("git status --porcelain").empty?

                push_to_git_remote(force:false)

                add_git_tag(tag:version)

                push_git_tags()

                push_pod

        end

        lane :push_pod do |options|
                pod_push(path: "AKPickerView-Swift.podspec", repo: "urbi-mobility", allow_warnings:true)
        end



end
